### PR TITLE
Fix: To Jsonify helper script output

### LINKED ISSUE #1127: When json format is used we should print the output of post update scripts in a json format
Swupd calls several commands using exec() and we redirect the output of the command to stdout and stderr. Instead we could read it and print using log functions so we would have them printed in a json format.
Another possible approach is redirect every output of exec() to stderr, so it wouldn't clash with json printed in stdout.

### PR DESCRIPTION
**Pull request by karthikprabhuvinod**
Earlier the output of each helper script
run through execve was redirected directly
to the standard-output or standard error.
Hence messages printed like raw strings even if
json-format was selected

This fix ensures that we redirect the output of those
scripts to swupd so that we get a chance to process them
or format them before printing

Fixes #1127

### CODE REVIEW

File: src/lib/sys.c [hunk 1]
```diff
@@ -68,6 +57,14 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
 
 	// Main
 	if (pid > 0) {
+		close(pipe_fds[1]);
+		char *line = NULL;
+		size_t len = 0;
+
+		while ((getline(&line, &len, pipe_fds[0])) != -1) {
```
Comment (otaviobp) [inline src/lib/sys.c]: getline can't be used with a file descriptor. You need to use read() here.

File: src/lib/sys.c [hunk 2]
```diff
@@ -93,12 +91,16 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
 	}
 	close(null_fd);
 
-	if (replace_fd(STDOUT_FILENO, stdout_file) < 0) {
```
Comment (otaviobp) [inline src/lib/sys.c]: We still need the replace_fd when stdout_file or stderr_file is set. We need them for:

    run_command_full("file1", "file2", "/usr/bin/ls", "/tmp", NULL);  
    run_command_quiet("/usr/bin/ls", "/tmp", NULL);

File: src/lib/sys.c [hunk 3]
```diff
@@ -93,12 +91,16 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
...
-		goto error_child;
+	if (stdout_file) {
```
Comment (otaviobp) [inline src/lib/sys.c]: I think you want the opposite. If (!stdout_file) we are printing to stdout, so we want to redirect.

File: src/lib/sys.c (hunk 1 above)
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Ya i realized that..got a mighty seg fault 🗡

File: src/lib/sys.c (hunk 3 above)
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: So if you check the code,

a.) if stdout_file arg is null, replace_fds returns a zero which it will print to STDOUT.
b.) if stdout_file arg is not null, replace_fds returns a replaced fd which points to a file

So I feel it is correct.

File: src/lib/sys.c (hunk 1 above)
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: done

File: src/lib/sys.c (hunk 2 above)
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Done

File: src/lib/sys.c (hunk 3 above)
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Done

File: src/lib/sys.c [hunk 4]
```diff
@@ -68,18 +75,27 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
 
 	// Main
 	if (pid > 0) {
+		close(pipe_fds[1]);
+		char buf[4096];
+
+		while ((read(pipe_fds[0], buf, 4096)) != 0) {
+			info("external command : %s", buf);
```
Comment (otaviobp) [inline src/lib/sys.c]: I'm still unsure on what prefix to use here. @castulo Any idea on this?

File: src/lib/sys.c [hunk 5]
```diff
@@ -101,6 +117,18 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
 		goto error_child;
 	}
 
+	if (!stdout_file) {
+		if (dup2(pipe_fds[1], STDOUT_FILENO) < 0) {
+			goto error_child;
+		}
+	}
```
Comment (otaviobp) [inline src/lib/sys.c]: you can move the replace_fd into an else clause here to make it clear that we are only replacing the fd if stdout_file != NULL

Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Done

File: src/lib/sys.c [hunk 6]
```diff
@@ -59,6 +60,12 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
 	int pid, ret, child_ret;
 	const char *cmd = params[0];
 	int null_fd;
+	int pipe_fds[2];
+
+	if (pipe(pipe_fds) < 0) {
```
Comment (otaviobp) [inline src/lib/sys.c]: Use pipe2(pipe_fds, O_CLOEXEC) to prevent leaking the pipe

Comment (karthikprabhuvinod) [reply src/lib/sys.c]: okay

Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Looks like when I build with it, it is just not able to find its declaration

Comment (karthikprabhuvinod) [reply src/lib/sys.c]: 65 |  if (pipe2(pipe_fds, O_CLOEXEC) < 0) {
      |      ^~~~~
      |      pipe
src/lib/sys.c:65:6: warning: nested extern declaration of ‘pipe2’ [-Wnested-externs]
  CCLD     swupd

File: src/lib/sys.c [hunk 7]
```diff
@@ -68,18 +75,28 @@ int run_command_full_params(const char *stdout_file, const char *stderr_file, ch
 
 	// Main
 	if (pid > 0) {
+#define MAX_BUFFER_SIZE 1024
+		close(pipe_fds[1]);
+		char buf[MAX_BUFFER_SIZE];
+
+		while ((read(pipe_fds[0], buf, MAX_BUFFER_SIZE)) != 0) {
```
[the remark this answers is not in the document]
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Done! Thanks, This is good tip!

File: src/lib/sys.c (hunk 6 above)
Comment (otaviobp) [reply src/lib/sys.c]: According to the pipe2 manpage you need to

       #define _GNU_SOURCE
       #include <fcntl.h>
       #include <unistd.h>

Adding _GNU_SOURCE should fix this

Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Yes it fixed it..

Comment (karthikprabhuvinod) [reply src/lib/sys.c]: Thanks.. looks like we support both POSIX and GNU linux extensions

File: src/lib/sys.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (karthikprabhuvinod) [reply src/lib/sys.c]: This is a much better approach but the only downfall I see is somebody earlier trying to parse  one dict has to parse several more. Just makes parsing logic slightly trickier in that case .But the code is more accurate this way.
