### PR TITLE
Timeout for testing connection in swupd init

### LINKED ISSUE #669: If clearlinux default server goes down, swupd won't update from alternative mirror
If you set the mirror using "swupd mirror --set" command and then tries to update your system, swupd checks if the mirror isn't very outdated. In this process, if the upstream mirror is down, swupd will fail to update from the alternative mirror.

And swupd check-update will work, so versions printed are divergent.

### PR DESCRIPTION
**Pull request by castulo**
As part of the swupd initialization, curl is initialized, which means it
is configured and the connection is tested. When configuring curl for
this test, no timeout was being configured, which was causing curl to
hang waiting for a response from the server if the server was unresponsive.

This commit configures the curl timeouts the same way they are being
configured when downloading files, so in case we get an unresponsive
server (or mirror) it doesn't get stuck forever.

Closes #669

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/curl.c [hunk 1]
```diff
@@ -105,6 +128,11 @@ static int check_connection(const char *test_capath)
 		return -1;
 	}
 
+	curl_ret = swupd_curl_set_timeouts(curl);
```
Comment (otaviobp) [inline src/curl.c]: I was reviewing curl.c source code and I think it's better to call swupd_curl_set_basic_options()  on check_connection to use all other configurations for curl as any other connection

Comment (castulo) [reply src/curl.c]: _swupd_curl_set_basic_options()_ receives a url as parameter. Since this is part of the swupd init I can use version_url or content_url.

**Comment by castulo** [comment]
The slow-server test is failing to initialize curl (getting error ECURL_INIT, cannot initialize curl agent)

File: src/curl.c [hunk 2]
```diff
@@ -116,6 +139,11 @@ static int check_connection(const char *test_capath)
 		return -1;
 	}
 
+	curl_ret = swupd_curl_set_basic_options(curl, content_url);
```
Comment (otaviobp) [inline src/curl.c]: Use version_url here so you can remove the line 121 (set CURLOPT_URL).
You can remove swupd_curl_set_optional_client_cert() call too, because this is also set by swupd_curl_set_basic_options()

Comment (castulo) [reply src/curl.c]: you are right, actually there were another couple more options that were already set in swupd_curl_set_basic_options(), I removed those too

**Comment by otaviobp** [comment]
Merging is always nice, but not sure if it's an easy task. 
It looks like a copy and paste from do_HEAD method from SimpleTest to support that in TestServer. if this is the case, I would go with the 2nd alternative

**Comment by otaviobp** [comment]
oops, I didn't realize SImpleTest depended on hang_server. It looks easier to go with the 1st alternative then

**Comment by castulo** [comment]
> oops, I didn't realize SImpleTest depended on hang_server. It looks easier to go with the 1st alternative then

what do you mean SimpleTest depended on hang_server?
