### PR TITLE
Configurable download retries

### LINKED ISSUE #211: Retry code rework
The retry code in swupd is not an ideal implementation, making it difficult to use throughout the code base. Some parts retry differently based on needing to support retries for network errors, or retry based on IO errors. Refactoring this code into a consistent, callable implementation would benefit many codepaths and potentially reduce the complexity and obscure bugs.

### LINKED ISSUE #322: configurable download retries
I am writing tests for issue #249 that simulate network errors. Right now, the tests run very slowly due to the hard-coded retry interval of 10 seconds and MAX_TRIES = 3.

Can interval and max retries be made configurable?

How do you handle this in your own tests?

On a related note, I am seeing "swupd update" trying to download Manifest.MoM.tar four times, for an overall duration of 1:10min. It all depends on the definition of MAX_TRIES of course, but to me this looks like an off-by-one error.

If we had a command line option --max-tries=3, I would expect three GET requests at most. For --max-retries=3, one initial GET followed by three retries would also make sense.

It's trying the second manifest only once.

HTTP log:
```
2017-10-20 14:32:04,915 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:32:14,776 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:32:34,717 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:33:14,724 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:33:14,752 - oe-selftest - INFO - "GET /20/Manifest.MoM.tar HTTP/1.1" 500 -
````

Output:
```
Attempting to download version string to memory
Update started.
Preparing to update from 10 to 20
Failed to retrieve 10 MoM manifest
Retry #1 downloading from/to MoM Manifests
Failed to retrieve 10 MoM manifest
Retry #2 downloading from/to MoM Manifests
Failed to retrieve 10 MoM manifest
Retry #3 downloading from/to MoM Manifests
Failed to retrieve 10 MoM manifest
Failure retrieving manifest from server
Update took 69.8 seconds
```

This is with file:// version URL and http:// content URL. Conceptually this tests mirrors a functioning version server while the content server has some internal issue.

### PR DESCRIPTION
**Pull request by castulo**
This PR tackles two main issues in download retries:

- Sync download retries were handled all over the place in the base code. This PR removes the retries from all those places and adds a single place for retrying a download, making the code more consistent and a lot easier to follow and maintain.

- Download retries where hardcoded to 3 in the case of sync downloads and to 5 in the case of async downloads. This PR add options to allow users to configure how many download retries they want swupd to do, and how long to wait between retries. This will be helpful for users in networks with unreliable connections, and will also help developers testing the code that were facing long wait times when simulating network problems.

Closes #211 
Closes #322

### CODE REVIEW

File: src/curl.c [hunk 1]
```diff
@@ -539,7 +526,91 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
 		unlink(filename);
 	}
 
-	return err;
+	return -status;
```
Comment (otaviobp) [inline src/curl.c]: You could return status here and change the return of this function from in to enum download_status

File: test/functional/usability/usa-download-retries.bats [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+	port=$(get_web_server_port "$TEST_NAME")
+	# set the versionurl and contenturl to point to the web server
+	set_upstream_server "$TEST_NAME" http://localhost:"$port"
+
+}
+
+@test "USA005: Retries for failed downloads can be configured" {
+
+	# Users should be able to configure the retry of a failed download using
+	# two options --max-retries and --retry-delay
```
Comment (otaviobp) [inline test/functional/usability/usa-download-retries.bats]: trailing space here

File: src/curl.c [hunk 3]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+
+	for (;;) {
+
+		/* download file */
+		ret = swupd_curl_get_file_full(url, filename, in_memory_file, resume_ok);
+
+		if (ret == DOWNLOAD_STATUS_COMPLETED) {
+			/* operation successful */
+			break;
+		} else {
```
Comment (otaviobp) [inline src/curl.c]: It's easier to read if you take this else out because break is going to get out of the for.

File: src/curl.c [hunk 4]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+			/* operation failed, determine retry strategy (only if the content
+			 * URL is not local). The value of ret on error will be < 0 */
+			current_retry++;
+			if (content_url_is_local) {
```
Comment (otaviobp) [inline src/curl.c]: you can move this to determine_strategy()

File: src/curl.c [hunk 5]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+			}
+			switch (strategy) {
+			case DONT_RETRY:
+				/* don't retry just return the failure */
+				return ret;
+			case RETRY_NOW:
+				/* if we have reached the retry limit just return the failure,
+				 * if not try again immediately */
+				if (max_retries) {
+					if (current_retry <= max_retries) {
```
Comment (otaviobp) [inline src/curl.c]: current_retry < max_retries.

current_retry starts with 0. So in the first retry it will be 1. if max_retries is 1 we shouldn't retry.

File: src/curl.c [hunk 6]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+				strategy = determine_strategy(-ret);
+			}
+			switch (strategy) {
+			case DONT_RETRY:
+				/* don't retry just return the failure */
+				return ret;
+			case RETRY_NOW:
+				/* if we have reached the retry limit just return the failure,
+				 * if not try again immediately */
+				if (max_retries) {
```
Comment (otaviobp) [inline src/curl.c]: You don't need an exception for this case. If max_retries is 0 we just won't retry.

File: src/curl.c [hunk 7]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+			case RETRY_WITH_DELAY:
+				/* if we have reached the retry limit just return the failure,
+				 * if not, wait for the delay and try again */
+				if (max_retries) {
+					if (current_retry <= max_retries) {
+						if (sleep_time) {
+							fprintf(stderr, "Waiting %d seconds before retrying the download\n", sleep_time);
+						}
+						fprintf(stderr, "Retry #%d downloading from %s\n", current_retry, url);
+						sleep(sleep_time);
```
Comment (otaviobp) [inline src/curl.c]: We have too much code duplication here. Instead of using a switch we can use an if just to set the sleep time:

    if (strategy == DONT_RETRY) {
       ....
       return;
    }
    
    if (current_retry <= max_retries) {
        fprintf(stderr, "Retry #%d downloading from %s\n", current_retry, url);
        if (strategy == RETRY_WITH_DELAY) {
            sleep(sleep_time);
            ...
        }
        continue;
....

File: src/curl.c [hunk 8]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+		return RETRY_NOW;
+	case DOWNLOAD_STATUS_ERROR:
+	case DOWNLOAD_STATUS_TIMEOUT:
+		return RETRY_WITH_DELAY;
+	default:
+		return RETRY_NOW;
+	}
+}
+
+static int retry_download(const char *url, char *filename, struct curl_file_data *in_memory_file, bool resume_ok)
```
Comment (otaviobp) [inline src/curl.c]: I would change the name of this function. It's not just retrying. it's trying and then retrying. First time I read this name I though that this function would be called only when we had a download failed.

File: src/curl.c [hunk 9]
```diff
@@ -539,7 +526,107 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
+			current_retry++;
+			if (content_url_is_local) {
+				strategy = DONT_RETRY;
+			} else {
+				strategy = determine_strategy(-ret);
+			}
+			switch (strategy) {
+			case DONT_RETRY:
+				/* don't retry just return the failure */
+				return ret;
```
Comment (otaviobp) [inline src/curl.c]: return an error code from errno instead of a negative status code.

File: src/curl_async.c [hunk 10]
```diff
@@ -194,7 +191,7 @@ void *swupd_curl_parallel_download_start(size_t max_xfer)
 
 	h->max_xfer = max_xfer;
 	h->curl_hashmap = hashmap_new(SWUPD_CURL_HASH_BUCKETS, file_hash_cmp, file_hash_value);
-	h->timeout = RETRY_TIMEOUT;
+	h->timeout = retry_delay;
```
Comment (otaviobp) [inline src/curl_async.c]: Can you rename h->timeout too? Because it's not a timeout

File: test/functional/usability/usa-download-retries.bats (hunk 2 above)
Comment (castulo) [reply test/functional/usability/usa-download-retries.bats]: fixed

File: src/curl.c (hunk 4 above)
Comment (castulo) [reply src/curl.c]: you are right, I don't remember the reason why I decided to have that check outside of the determine_strategy function, but based on how the code looks now it totally makes sense. I'll fix that.

File: src/curl.c (hunk 3 above)
Comment (castulo) [reply src/curl.c]: I'm not sure I understand what you mean on this one

Comment (castulo) [reply src/curl.c]: can you elaborate a little more please?

File: src/curl.c (hunk 5 above)
Comment (castulo) [reply src/curl.c]: current_retry is being pre incremented before getting to that if, so it is really as if it started at 1, not 0, so if the user set up a max_retry of 1, if there is a download failure it will retry once and give up. The functional tests added verify the correct behavior of this check them out.

File: src/curl.c (hunk 6 above)
Comment (castulo) [reply src/curl.c]: yes, the if is only so I could print a message saying that retries are disabled.

File: src/curl.c (hunk 7 above)
Comment (castulo) [reply src/curl.c]: yes, but I just thought that using a switch would look cleaner than using ifs, but if you think having less lines of code is better I can change that code to use ifs instead of a switch

File: src/curl.c (hunk 8 above)
Comment (castulo) [reply src/curl.c]: ok, I named it like that because the implementation is based on the "retry" pattern. Let me think on a different name then....

File: src/curl_async.c (hunk 10 above)
Comment (castulo) [reply src/curl_async.c]: Good idea

File: src/curl.c (hunk 3 above)
Comment (otaviobp) [reply src/curl.c]: No. You just don't need this else here and it's easier to read because the code won't have an extra indentation

    for (;;) {
             ret = swupd_curl_get_file_full(url, filename, in_memory_file, resume_ok);
            if (ret == DOWNLOAD_STATUS_COMPLETED) {
                break; //Or you can add a return here instead of the break
            }
             /*code that is in the else come here*
    }

File: src/curl.c (hunk 5 above)
Comment (otaviobp) [reply src/curl.c]: Sorry, I didn't notice that. You're right.

File: src/curl.c (hunk 6 above)
Comment (otaviobp) [reply src/curl.c]: Well I think it's better to print a message saying that it's disabled. You can leave this here.

File: src/curl_async.c (hunk 10 above)
Comment (castulo) [reply src/curl_async.c]: Done

File: src/curl.c (hunk 7 above)
Comment (otaviobp) [reply src/curl.c]: It's not about saving lines, but in reducing code duplication. printfs for example are hard to maintain if they are duplicated.

File: src/curl.c (hunk 8 above)
Comment (castulo) [reply src/curl.c]: what about _retry_download_loop_ ? or what do you suggest?

Comment (otaviobp) [reply src/curl.c]: good

Comment (castulo) [reply src/curl.c]: done

File: src/curl.c (hunk 3 above)
Comment (castulo) [reply src/curl.c]: done

File: src/curl.c (hunk 1 above)
Comment (castulo) [reply src/curl.c]: The problem here is that the **_process_curl_error_codes_** function which is called by **_swupd_curl_get_file_full_** used to return a negative errno number, and with this refactoring those errnos were removed from the function so it now returns a positive **_enum download_status_**. Most functions that make use of this function only check for values !=0 to determine if the file was gotten successfully by curl, but some functions (like _get_latest_version_ rely on the negative value that the function used to return). So bottom line is that to make this change we will need to scan many other functions to make sure they won't break if we change the return value from negative to positive.

File: src/curl.c (hunk 9 above)
Comment (castulo) [reply src/curl.c]: This is related to the same comment I made above.

File: src/curl.c (hunk 1 above)
Comment (otaviobp) [reply src/curl.c]: The problem with the suggested approach is that it is inconsistent. It's not a good idea to use different return codes in  the same function. For example, in this case, if curl hasn't been initialized, or if there's any error in curl api calls, swupd_curl_get_file_full returns -1. When you use this value by doing determine_strategy(-ret), we assume the status code is 1 (DOWNLOAD_STATUS_PARTIAL_FILE), what's incorrect.

You don't need to propagate the return value all over. The only user of swupd_curl_get_file_full is retry_download, so it's ok to change the return code from download_status.

And I would change retry_download to download a negative errno code, to be compatible with other functions in the API.

File: src/curl.c (hunk 9 above)
Comment (castulo) [reply src/curl.c]: Done

File: src/curl.c (hunk 1 above)
Comment (castulo) [reply src/curl.c]: Done

**Comment by castulo** [comment]
@otaviobp all your comments have been addressed. 👍
