### PR TITLE
download: Process all completed downloads in poll_fewer_than()

### LINKED ISSUE #582: swupd fails to install in a root during `mixer build image`: Too many open files
This happens during mixer image builds. We isolated the failing command to
`sudo -E swupd verify --install --path=poo --manifest=latest --contenturl=file:///home/clear/mix/update/www --versionurl=file:///home/clear/mix/update/www --format=25 --statedir=/home/clear/mix/lmao --certpath=/home/clear/mix/Swupd_Root.pem` And this produces the following failure:

```
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.ac452282255628aef7c7e84aea5389db1c9719e6630c0d7a088ee9e65e81c21d.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.b3659d3bd11f8e05b8a130dd395245c93e4063abf08afaa8d76247333ba70a89.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.ad80bb8dadd30f72facb3fa0b427302777d1f5d90f660bf538513c5da3c53f43.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.bd358fe7a5729a701bf506db65b872f975ae38931b4db95c93aabcc667cce3f2.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.48c19098253ddb0aeef2d440732b2fa3eb0bbac570e234b20c1e37f305e0f37b.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.b8249ad2c461fe1e65ad1a9377e6f06dd2c4fa4d00ab8e658fe6b2c0783d24d7.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.e30fe099a2e36dfd6a1ddc9f638fadaf5fed3ddbdaf7a5c0e2ecce4b7c68d80e.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.25dbf85ea6f4bdef23410b2fa9f0fbeba0bb4d0845bfbe43fe72fe7ad804593d.tar",strerror="Too many open files"*\
Cannot open file for write \*outfile="/home/clear/mix/lmao/download/.be22eb817b896213dbd0c5d8701773ec4089d5f79bec6521cf167f4cd8a7938a.tar",strerror="Too many open files"*\
```

Interestingly, the start of the log looks as follows:

```
Verifying version 10
Downloading packs...
	...40%zero pack downloads failed. 
Failed - Server-side error, cannot download necessary files
Verifying files
	...100%
Starting download of remaining update content. This may take a while...
```

After that it floods the 'too many open files' error forever, stuck in a loop.

### PR DESCRIPTION
**Pull request by otaviobp**
When downloading from file:// curl can process all reads and writes on the
first call of curl_multi_process() and then curl_multi_wait() will set numfds
to 0 and poll_fewer_than() will return without processing the download (i.e
extracting it).

Also change a bit the poll_fewer_than() to follow the timeout approach from the
official curl_multi_wait() example (https://curl.haxx.se/libcurl/c/multi-single.html).

Fixes #582

Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>

### CODE REVIEW

**Comment by bryteise** [comment]
Ah nice, good to know this is only impacting local files. Great find!

File: src/download.c [hunk 1]
```diff
@@ -306,18 +310,51 @@ static int perform_curl_io_and_complete(struct swupd_curl_parallel_handle *h, in
...
+
+	ret = curl_multi_wait(mcurl, NULL, 0, CURL_MULTI_TIMEOUT, &numfds);
+
+	// If numfds is zero curl_multi_wait reached a timeout or there isn't
+	// any fd to process. The first ocurrence we assume it's a timeout.
+	// After that we assume we need to force a sleep before calling
+	// curl_multi_wait() again.
+	if (ret != CURLM_OK && !numfds) {
+		if (*repeats == 1) {
+			usleep(100000); // sleep 100ms
```
Comment (matthewrsj) [inline src/download.c]: you should #define this like you did with CURL_MULTI_TIMEOUT. It could be NOFD_WAIT or something

File: src/download.c [hunk 2]
```diff
@@ -306,18 +310,51 @@ static int perform_curl_io_and_complete(struct swupd_curl_parallel_handle *h, in
...
+  * There's a protection to avoid having a download queue larger than
+  * xfer_queue_high + XFER_QUEUE_BUFFER in cases where curl doesn't have any
+  * data to process for any download. In this case we will return an error and
+  * the caller is in charge of setting the last download to be retried.
+  */
 static int poll_fewer_than(struct swupd_curl_parallel_handle *h, size_t xfer_queue_high, size_t xfer_queue_low)
 {
 	CURLMcode curlm_ret;
-	int running;
+	int running = 1;
```
Comment (matthewrsj) [inline src/download.c]: use the available `bool` type please.

Comment (otaviobp) [reply src/download.c]: We can't use bool type for running because it's used by a curl API that requires an int. I'm assuming your comment is about the repeats variable that can be a bool variable. I'll fix that. thanks

**Comment by matthewrsj** [comment]
We need another review here, @evil-brain
