### PR TITLE
Use verify --fix --picky with older versions

### LINKED ISSUE #608: "swupd verify --fix --picky -m <ver>" fails if a bundle doesn't exist in <ver>
I was at Clear ver 25180.  This was when the zstd bundle was introduced into my system.  I tried to "swupd verify --fix --picky -m 24180" and it failed because zstd didn't exist back then.  swupd gave a warning that the bundle is invalid and "skipping it...", errored out, and stopped.

The workaround was to manually delete the offending bundle(s) in /usr/share/clear/bundles/ and retry "swupd verify --fix --picky...".  This is what I think swupd should do automatically.

### PR DESCRIPTION
**Pull request by castulo**
When you do a "verify --fix --picky -m older_version", and one
or more of the currently installed bundles didn't exist back then,
a non useful error message was being used, and the verify operation
would fail.

This commit makes the following changes.

1) With this commit, if the mentioned situation happens, the verify
operation will still be stopped, but a useful message will now be
displayed to inform the user of the situation, and he/she will be
presented with an alternative to proceed using the --force option.

2) If the user uses the --force option, the user will still be warned
but the verify operation will continue and the offending bundles will
be removed from the system.

3) Fixes a bug when using verify --picky. Only files that were orphaned
were being counted as files being removed from the system, files removed
because of the picky options were not being counted. This commit fixes
that.

Closes #608

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/extra_files.c [hunk 1]
```diff
@@ -90,26 +90,33 @@ static int qsort_helper(const void *A, const void *B)
...
 	}
+
+	/* return true if the function deleted a file or directory, false otherwise */
+	return ret;
 }
 
 /* expect the start to end in /usr and be the absolute path to the root */
-int walk_tree(struct manifest *manifest, const char *start, bool fix, const regex_t *whitelist)
+int walk_tree(struct manifest *manifest, const char *start, bool fix, const regex_t *whitelist,
+	      int *extraneous_files, int *files_deleted, int *files_not_deleted)
```
Comment (icarus-sparry) [inline src/extra_files.c]: Rather than adding 3 int* parameters, consider adding a pointer to a struct that contains 3 integers.

Comment (castulo) [reply src/extra_files.c]: Thanks for reviewing @icarus-sparry , that was a good suggestion. I have pushed an update that includes a struct for keeping those file counts. Please let me know if you have any concern with the new implementation.

File: src/verify.c [hunk 2]
```diff
@@ -818,6 +818,27 @@ int verify_main(int argc, char **argv)
 	}
 
 	ret = add_included_manifests(official_manifest, &subs);
+	/* if we are verifying against an older version, and one or more bundles were
+	 * not found, continue only if --force was used since those bundles will be
+	 * removed */
+	if (version < sys_version && ret == -add_sub_BADNAME) {
```
[the remark this answers is not in the document]
Comment (castulo) [reply src/verify.c]: hmm, yeah you are probably right, I guess that could happen if for example a bundle was removed in a newer version

**Comment by castulo** [comment]
@otaviobp I made the changes you requested and I also took the opportunity to regroup the changes into more appropriate commits according to what they were doing so they are more organized.

**Comment by otaviobp** [comment]
Fixed proposed changes, added --no-scripts to verify and update commands, added a new variable $BUNDLE_LIST to make it possible to run a faster test and added a new test to check if fullfile downloads are working.

To run it in the fast mode just do:

    $ BUNDLE_LIST=os-core bats -t test/real_content/test_swupd.bats

**Comment by otaviobp** [comment]
oops, commented in the wrong PR

File: src/verify.c [hunk 3]
```diff
@@ -818,6 +818,27 @@ int verify_main(int argc, char **argv)
...
+		if (force) {
+			if (cmdline_option_fix && cmdline_option_picky) {
```
[the remark this answers is not in the document]
Comment (otaviobp) [reply src/verify.c]: That's right. Even bundle-list will list the bundle.

File: src/extra_files.c [hunk 4]
```diff
@@ -90,29 +90,36 @@ static int qsort_helper(const void *A, const void *B)
...
+			fprintf(stderr, "Removing %s failed: %s\n", temp, strerror(errno));
+			ret = false;
 		}
 		free_string(&temp);
 	} else {
 		printf("%s%s\n", filename, is_dir ? "/" : "");
+		ret = false;
 	}
+
+	/* return true if the function deleted a file or directory, false otherwise */
```
Comment (icarus-sparry) [inline src/extra_files.c]: I would put this comment just before the 'static bool handle' definition line, and then question if it was correct. In the case that you are attempting to remove a directory but fail you may well delete some files but still return false.

Perhaps a better comment would be "return true if the function deletes the specified filename, otherwise false".

Failure examples are hard, because you are running as root, but could happen. A race condition where a new file is added to a directory whilst `remove` is busy removing a subtree might cause the eventual removal of the directory to fail as it is not empty. A read-only file system might be mounted on a sub directory.

Thank you for the struct file_counts change - I think it is good.

Comment (castulo) [reply src/extra_files.c]: I really appreciate your comments @icarus-sparry I/m learning so much. Thanks for reviewing. I'll update the comment as you suggested.
