### PR TITLE
Fix logger format when printing debug messages

### LINKED ISSUE #1009: `--debug` flag should also suppress progress
There's a new flag `--no-progress` and I was checking whether it's mutually exclusive with `--debug` flag.

It seems to me that when there is `--debug`, it'd be better to suppress the progress as if `--no-progress` is also specified. Below are the output for adding `gvim` bundle, where the first one only has `--debug` and looks messy.

```
❯ sudo swupd bundle-add gvim --debug                          
2019-07-17 20:20:15 (src/curl.c:136)              Debug: Curl - check_connection url: https://cdn.download.clearlinux.org/update
2019-07-17 20:20:15 (src/bundle.c:777)            Loading required manifests...
2019-07-17 20:20:16 (src/packs.c:248)             No packs need to be downloaded
2019-07-17 20:20:16 (src/fullfile.c:158)          No extra files need to be downloaded
2019-07-17 20:20:16 (src/bundle.c:935)            Installing bundle(s) files...
2019-07-...100%2019-07-17 20:20:16 (src/lib/progress.c:123)      
2019-07-17 20:20:16 (src/scripts.c:146)           Calling post-update helper scripts
2019-07-17 20:20:41 (src/bundle.c:1077)           Successfully installed 1 bundle
```

```
❯ sudo swupd bundle-add gvim --debug --no-progress                    
2019-07-17 20:21:00 (src/curl.c:136)              Debug: Curl - check_connection url: https://cdn.download.clearlinux.org/update
2019-07-17 20:21:00 (src/bundle.c:777)            Loading required manifests...
2019-07-17 20:21:01 (src/packs.c:248)             No packs need to be downloaded
2019-07-17 20:21:01 (src/fullfile.c:158)          No extra files need to be downloaded
2019-07-17 20:21:01 (src/bundle.c:935)            Installing bundle(s) files...
2019-07-17 20:21:01 (src/scripts.c:146)           Calling post-update helper scripts
2019-07-17 20:21:26 (src/bundle.c:1077)           Successfully installed 1 bundle
```

### PR DESCRIPTION
**Pull request by castulo**
Debug messages need to be treated a little differently from other
messages, since they include more information, like the time, file and
line of code. So certain things like having carriage returns and
messages with only a line break should not be allowed since they would
mess up the debug output.

This commit fixes that issue

Closes #1009

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/lib/log.c [hunk 1]
```diff
@@ -57,12 +66,22 @@ static void log_internal(FILE *out, const char *file, int line, const char *labe
...
+		if (format[strlen(format) - 1] != '\n') {
+			format_end = "\n";
+		}
 	}
 
 	if (label) {
 		fprintf(out, "%s: ", label);
 	}
 	vfprintf(out, format, args_list);
+	fprintf(out, "%s", format_end);
```
Comment (otaviobp) [inline src/lib/log.c]: I like the idea, but I'd move the if here so you won't need to have another variable for that.

File: src/lib/log.c [hunk 2]
```diff
@@ -57,12 +66,22 @@ static void log_internal(FILE *out, const char *file, int line, const char *labe
...
+
+exit:
 	fflush(out);
```
Comment (otaviobp) [inline src/lib/log.c]: This was added by a previous patch, but adding a fflush() is usually not a good idea because it can slow down swupd when there's too much logs.
What is the problem to remove this?

File: src/lib/log.c (hunk 1 above)
Comment (castulo) [reply src/lib/log.c]: Well the if cannot be moved because the time(file:line) has to be printed before the message. I thought of adding another if (cur_log_level == LOG_DEBUG) {} here but using a variable seemed cleaner. But I can use another if instead if you think is better.

File: src/lib/log.c (hunk 2 above)
Comment (castulo) [reply src/lib/log.c]: I don't remember why I added it in a previous patch, I remember when it wasn't there the output was not correctly printed. But we could remove it and see how it goes. And add it back if we see is necessary.

Comment (otaviobp) [reply src/lib/log.c]: yes. it would be nice to test that

File: src/lib/log.c (hunk 1 above)
Comment (otaviobp) [reply src/lib/log.c]: I prefer to have another if. And then we won't call fprintf again.

**Comment by castulo** [comment]
Fixed all the reported issues

File: src/lib/log.c [hunk 3]
```diff
@@ -38,14 +38,22 @@ static void log_internal(FILE *out, const char *file, int line, const char *labe
 	struct tm *timeinfo;
 	int printed;
 
-	/* if the message starts with '\n' add a line break before the message */
+	/* if the message starts with '\n' add a line break before the message
+	 * unless we are printing in debug mode, or to a file because that would
+	 * mess up the output, if that is the case remove those characters */
 	while (strncmp(format, "\n", 1) == 0 || strncmp(format, "\r", 1) == 0) {
-		if (out == stdout || out == stderr) {
+		if ((out == stdout || out == stderr) && (cur_log_level != LOG_DEBUG)) {
```
Comment (otaviobp) [inline src/lib/log.c]: shouldn't we print '\n' even if we are using --debug?

File: src/lib/log.c [hunk 4]
```diff
@@ -38,14 +38,22 @@ static void log_internal(FILE *out, const char *file, int line, const char *labe
...
 			fprintf(out, "%c", format[0]);
 		}
 		format++;
 	}
 
+	/* if the message was empty or had only line breaks or carriage return
+	 * finish here, otherwise we could print empty debug info or labels */
+	if (strcmp(format, "") == 0) {
```
Comment (otaviobp) [inline src/lib/log.c]: Is this a real case? Are we using empty prints?

File: src/lib/log.c (hunk 3 above)
Comment (otaviobp) [reply src/lib/log.c]: the only command that is printing \r now is the progress report. I'd change it to print \n instead if debug is used.
And stop handling \r here.

Comment (castulo) [reply src/lib/log.c]: > shouldn't we print '\n' even if we are using --debug?

What I was thinking is that the "\n" at the beginning of the lines are mostly used to space messages between each other to improve the looks of the output. When using --debug you are printing more information, so the output doesn't really need that extra spacing and printing line break would result in debug messages that look like this:
```
2019-07-23 17:46:27 (src/curl.c:570)              Debug: some debug message
2019-07-23 17:46:27 (src/curl.c:438)              Debug: more messages
2019-07-23 17:46:27 (src/curl.c:579)              
2019-07-23 17:46:27 (src/bundle.c:777)            Bla bla bla
```
But maybe it is ok to print those empty lines even in debug mode. What do you think?

Comment (castulo) [reply src/lib/log.c]: > the only command that is printing \r now is the progress report. I'd change it to print \n instead if debug is used.
> And stop handling \r here.

The problem with handling it there instead of here is that here it would allow for more flexibility. I like the idea of being able to use \n and \r with the logger if necessary so you can format your output as you please. It is not very common that you would need to use the \r thing, but if you do, it would be supported.

File: src/lib/log.c (hunk 4 above)
Comment (castulo) [reply src/lib/log.c]: We are not using empty strings, but with this implementation, if someone is printing to a file and the code has for example a `info("\n")`, since the \n is going to be stripped from the message, the resulting message would be an empty string.

File: src/lib/log.c (hunk 3 above)
Comment (otaviobp) [reply src/lib/log.c]: I think we should always print something if the user of that lib calls the print function. For example if the user calls info("\n") I prefer to print an empty line than not printing anything. If we are debugging the output looking for a bug we are going to see prints in code that aren't printed on the output. And that makes things harder. Imagine one output like

    2019-07-23 17:46:27 (src/curl.c:570)              Debug: some debug message
    2019-07-23 17:46:27 (src/curl.c:438)              Debug: more messages
    2019-07-23 17:46:27 (src/curl.c:579)              
    Segmentation fault

We know that segfault occurred after that call and not before.

**Comment by castulo** [comment]
> I tested the output and it looks good, with the exception of empty lines. I think we should print them in debug mode. Debug mode isn't suppose to be used unless you are debugging a problem, so it's better to have more than less.
> I'm convinced that it's a good thing to handle the \r on log too.

I'll include those in debug mode then.

File: src/lib/log.c [hunk 5]
```diff
@@ -20,50 +20,88 @@
...
+
+static void log_internal(FILE *out, const char *file, int line, const char *label, const char *format, va_list args_list)
+{
+
+	char msg[LINE_MAX];
+
+	/* do not print the carriage return found at the beginning of the message if
+	 * in debug mode or if printing to a file, that would mess up the output */
+	while (strncmp(format, "\r", 1) == 0) {
+		if (cur_log_level != LOG_DEBUG && (out == stdout || out == stderr)) {
```
Comment (otaviobp) [inline src/lib/log.c]: I just test this again and this isn't working. '\r' are being outputted to a file. If you redirect the output to a file out is still going to be stdout or stderr. In progress we check if we are outputting to a tty using isatty().
I still prefer to remove this code and handle that only on progress. But as I said I'm ok to leave it here if you prefer. But check for tty instead.

File: src/lib/log.c [hunk 6]
```diff
@@ -20,50 +20,88 @@
...
+		}
+		format++;
+	}
 
-	/* if the message starts with '\n' add a line break before the message */
-	while (strncmp(format, "\n", 1) == 0 || strncmp(format, "\r", 1) == 0) {
+	/* do not print the line breaks found at the beginning of the message
+	 * only if printing to a file */
+	while (strncmp(format, "\n", 1) == 0) {
 		if (out == stdout || out == stderr) {
```
Comment (otaviobp) [inline src/lib/log.c]: same here. For me I would remove this if

File: src/lib/log.c (hunk 5 above)
Comment (castulo) [reply src/lib/log.c]: you are right, I will change this

File: src/info.c [hunk 7]
```diff
@@ -90,6 +90,13 @@ enum swupd_code info_main(int UNUSED_PARAM argc, char UNUSED_PARAM **argv)
 	}
 	progress_init_steps("info", steps_in_info);
 
+	warn("\r");
```
Comment (otaviobp) [inline src/info.c]: I think you forgot this test here. haha

File: src/lib/log.c [hunk 8]
```diff
@@ -20,50 +20,89 @@
...
-	vfprintf(out, format, args_list);
-	fflush(out);
+
+	/* all debug messages need to finish with a line break, even if the
+	 * user didn't add one to the message, otherwise the output will be
+	 * messed up
+	 * Note that the "\n" could have been provided as an argument to the
+	 * string, as in this example: info("example%s", flag ? "" : "\n")
+	 * so we need to pass the string to a variable first to inspect it */
+	vsnprintf(msg, LINE_MAX, format, args_list);
```
Comment (otaviobp) [inline src/lib/log.c]: when we replaced vfprintf() with vsnprintf() + fprintf()?

File: src/info.c (hunk 7 above)
Comment (castulo) [reply src/info.c]: 😫

File: src/lib/log.c (hunk 8 above)
Comment (otaviobp) [reply src/lib/log.c]: oh, I got it. to check the last \n

Comment (castulo) [reply src/lib/log.c]: I added an explanation why I did that. If we do something like this:
`info("example%s", flag ? "" : "\n")`

We need that so we can inspect the string to see if it already contains a "\n" at the end. If we remove that part we are going to be printing an extra blank line in debug mode in those cases, so it is not a big deal, if you prefer to print the extra line I can remove that and go back to using vfprintf()

Comment (otaviobp) [reply src/lib/log.c]: no, it's fine the way it was. I didn't get that at first

**Comment by castulo** [comment]
Removed the extra code I was using for testing.
