### PR TITLE
Fix download progress for fullfiles

### LINKED ISSUE #939: swupd shows incorrect progress report when doing repair
When running "swupd repair" to fix mismatching files in the system, at some point swupd needs to download fullfiles of the files that need to be repaired, when this is happening, swupd shows the progress of the download to the user. This progress is being reported incorrectly, it goes above 100%.
 
It looks like this:
```
Diagnosing version 29690
Verifying files
	...100%
Starting download of remaining update content. This may take a while...
	...101850%
Adding any missing files
	...100%
Repairing modified files
```

This bug can be reproduced by corrupting a system file then running `swupd clean --all` followed by `swupd repair`.

**Expected behavior**
When downloading the fullfiles swupd should show the progress going from 0% to 100%

**Environment (please complete the following information):**
 - Clear Linux OS Version: 29690
 - swupd version: 3.20.0

### PR DESCRIPTION
**Pull request by castulo**
When the download progress of fullfiles was being calculated it was
being done considering as if the files were being downloaded serially
not in parallel. This was causing an error in the calculation of the
download progress.

This commit fixes the issue by considering the files are being downloaded
in parallel when calculating the download progress.

Closes #939

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/curl_async.c [hunk 1]
```diff
@@ -157,6 +158,11 @@ static void free_curl_file(struct swupd_curl_parallel_handle *h, struct multi_cu
 		curl_easy_cleanup(curl);
 		file->curl = NULL;
 	}
+
+	if (file->progress != NULL) {
```
Comment (otaviobp) [inline src/curl_async.c]: you don't need to check for null before free. if pointer is null free() doesn't fail.

File: src/fullfile.c [hunk 2]
```diff
@@ -153,6 +153,25 @@ int download_fullfiles(struct list *files, int *num_downloads)
 		free_string(&targetfile);
 	}
 
+	/* remove tar duplicates from the list */
+	need_download = list_sort(need_download, file_sort_hash);
```
Comment (otaviobp) [inline src/fullfile.c]: Sorting a list is very expensive. We prevent a download to be performed twice by using the hashmap in curl_async. 
Do we need to filter files in this stage?

File: src/manifest.c [hunk 3]
```diff
@@ -77,6 +77,27 @@ int file_sort_filename_reverse(const void *a, const void *b)
...
+	struct file *A, *B;
+	int ret;
+	A = (struct file *)a;
+	B = (struct file *)b;
+
+	ret = strcmp(A->hash, B->hash);
+	if (ret) {
+		return ret;
+	}
+	if (A->is_deleted > B->is_deleted) {
```
Comment (otaviobp) [inline src/manifest.c]: we just add files to the list if if_deleted == 0. Why do we need this here?

**Comment by otaviobp** [comment]
lgtm

File: src/curl_async.c (hunk 1 above)
Comment (castulo) [reply src/curl_async.c]: nice! thanks for the tip, I'll remove the if

File: src/fullfile.c (hunk 2 above)
Comment (castulo) [reply src/fullfile.c]: yes, otherwise those files that are not actually going to be downloaded because use the same tar are going to be counted when we determine the total download size, then when we are reporting download progress we are never going to reach 100%

File: src/manifest.c (hunk 3 above)
Comment (castulo) [reply src/manifest.c]: we don't, I copied this function from `file_sort_filename` and forgot to remove that part

**Comment by castulo** [comment]
@otaviobp I addressed your comments, let me know if there is something else missing
