### PR TITLE
Http bug fixes

### LINKED ISSUE #598: Slow internet -> unclear if swupd just wastes my bandwidth and retries entire download several times
My internet sucks. It's so slow that almost any swupd bundle add, even smaller ones, cause swupd to timeout, even though the downloads progress. As a result, the output suggests that swupd throws the partial files out and starts from scratch, wasting bandwidth and time.

```
# sudo swupd bundle-add keepassxc 
Downloading packs...
	...100%
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 200 - Transferred a partial file
Starting download retry #1 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - Transferred a partial file
Starting download retry #2 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - No error
Starting download retry #3 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - No error
Starting download retry #4 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - Transferred a partial file
Starting download retry #5 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - Timeout was reached
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
```

This is a bug: If the download wasn't stalled, but is just slow, it shouldn't cause the download to interrupt and error, instead it should just continue downloading since data is readily flowing.

Also, the download should be retried if possible at the point it gave an error. It's entirely unclear if it did.

A resumed download is a warning at best, as well.

### PR DESCRIPTION
**Pull request by otaviobp**
fixes some problems in http downloads:
 - There were some http codes that aren't processed the way they should
 - Fix problem in download resume
 - Inform users when a download is resuming (request on #598)
 - Reduce the number of downloads in parallel when there are connection errors (like timeout) in downloads. Retry using 27, 9, 3, 1, 1, 1 downloads in parallel (requested on #598) 

Fixes #598 #562

### CODE REVIEW

File: src/curl.c [hunk 1]
```diff
@@ -311,6 +311,99 @@ CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file *file)
...
+enum download_status process_curl_error_codes(int curl_ret, CURL *curl_handle, int *err)
+{
+	char *url;
+	if (curl_easy_getinfo(curl_handle, CURLINFO_EFFECTIVE_URL, &url) != CURLE_OK) {
+		url = "<not available>";
+	}
+
+	if (curl_ret == CURLE_OK || curl_ret == CURLE_HTTP_RETURNED_ERROR) {
+		long response = 0;
+		if (curl_ret == CURLE_OK || curl_ret == CURLE_HTTP_RETURNED_ERROR) {
```
Comment (jwakre) [inline src/curl.c]: This condition is identical to the one on line 324, so it will always evaluate to true.

Comment (otaviobp) [reply src/curl.c]: True. this is a left over. I'll remove this conditional

File: src/curl_async.c [hunk 2]
```diff
@@ -549,6 +565,9 @@ int swupd_curl_parallel_download_end(void *handle, int *num_downloads)
 				list_free_item(l, NULL);
 				l = next;
 
+				// Retry was probably scheduled because of network problems, so
+				// reevaluate the number of parallel downloads
+				reevaluate_number_of_parallel_downloads(h, file->retries);
```
Comment (jwakre) [inline src/curl_async.c]: I'm just getting familiar with the download code, so I may be wrong here.

It looks like there can be a list of failed downloads that can each call reevaluate_number_of_parallel_downloads, even though they failed with the same MAX_XFER value. This would allow a few download failures to drop the MAX_XFER value from 27 -> 1 instead of incrementally.

File: src/curl.c [hunk 3]
```diff
@@ -311,6 +311,99 @@ CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file *file)
...
+			return DOWNLOAD_STATUS_COMPLETED;
+		case 403:
+			fprintf(stderr, "Curl: Download failed: Forbidden (403) - '%s'\n", url);
+			*err = -EPERM;
+			return DOWNLOAD_STATUS_FORBIDDEN;
+		case 404:
+			fprintf(stderr, "Curl: Download failed: File not found (403) - '%s'\n", url);
+			*err = -ENOENT;
+			return DOWNLOAD_STATUS_NOT_FOUND;
+		default:
```
Comment (castulo) [inline src/curl.c]: For consistency, in this case you can also print a generic error message like "Curl: Download failed."

File: src/curl.c [hunk 4]
```diff
@@ -311,6 +311,99 @@ CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file *file)
...
+		case CURLE_COULDNT_RESOLVE_PROXY:
+			fprintf(stderr, "Curl: Could not resolve proxy\n");
+			*err = -1;
+			return DOWNLOAD_STATUS_ERROR;
+		case CURLE_COULDNT_RESOLVE_HOST:
+			fprintf(stderr, "Curl: Could not resolve host - '%s'\n", url);
+			*err = -1;
+			return DOWNLOAD_STATUS_ERROR;
+		case CURLE_COULDNT_CONNECT:
+			fprintf(stderr, "Curl: Could not connect to host or proxy\n");
```
Comment (castulo) [inline src/curl.c]: you can also print the url in this message similar to the way you do it in the CURLE_COULDNT_RESOLVE_HOST

File: src/curl.c [hunk 5]
```diff
@@ -311,6 +311,99 @@ CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file *file)
...
+			*err = -ENONET;
+			return DOWNLOAD_STATUS_ERROR;
+		case CURLE_FILE_COULDNT_READ_FILE:
+			*err = -ENOENT;
+			return DOWNLOAD_STATUS_NOT_FOUND;
+		case CURLE_PARTIAL_FILE:
+			fprintf(stderr, "Curl: File incompletely downloaded from '%s''\n", url);
```
Comment (castulo) [inline src/curl.c]: you have an extra ' here

File: src/curl.c [hunk 6]
```diff
@@ -311,6 +311,99 @@ CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file *file)
...
+			return DOWNLOAD_STATUS_ERROR;
+		case CURLE_SSL_CERTPROBLEM:
+			fprintf(stderr, "Curl: Problem with the local client SSL certificate\n");
+			*err = -1;
+			return DOWNLOAD_STATUS_ERROR;
+		case CURLE_RANGE_ERROR:
+			fprintf(stderr, "Range command not supported by server, download resume disabled.\n");
+			*err = -ERANGE;
+			return DOWNLOAD_STATUS_RANGE_ERROR;
+		default:
```
Comment (castulo) [inline src/curl.c]: Same comment, you can add a generic error message.

File: src/curl.c [hunk 7]
```diff
@@ -386,103 +478,22 @@ static int swupd_curl_get_file_full(const char *url, char *filename,
...
-		case CURLE_RANGE_ERROR:
-			fprintf(stderr, "Range command not supported by server, download resume disabled.\n");
 
-			//Reset variables
-			ret = 0;
-			err = -1;
-			memset(&local, 0, sizeof(local));
+	status = process_curl_error_codes(curl_ret, curl, &err);
+	if (status == DOWNLOAD_STATUS_RANGE_ERROR) {
+		//Reset variable
```
Comment (castulo) [inline src/curl.c]: missing space

File: src/swupd-curl-internal.h [hunk 8]
```diff
@@ -31,6 +31,21 @@ extern CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file
  */
 extern CURLcode swupd_curl_set_basic_options(CURL *curl, const char *url);
 
+/* Download status code */
+enum download_status {
+	DOWNLOAD_STATUS_COMPLETED =0,
```
Comment (castulo) [inline src/swupd-curl-internal.h]: missing space

File: test/functional/update/update-slow-server.bats [hunk 9]
```diff
@@ -40,6 +40,7 @@ test_teardown() {
 		Downloading packs...
 		Curl: Partial file downloaded from '.*pack-test-bundle-from-10.tar'
 		Starting download retry #1 for .*100/pack-test-bundle-from-10.tar
```
Comment (castulo) [inline test/functional/update/update-slow-server.bats]: I know this is not part of this review, but we should consider adding the ' ' around the url from the message that goes like "Starting download retry ....", all other messages use it, so it would look more consistent.

File: src/curl_async.c [hunk 10]
```diff
@@ -34,7 +34,7 @@
 #include <unistd.h>
```
Comment (castulo) [inline src/curl_async.c]: Nice, this is a much better name for this file

File: src/curl_async.c (hunk 2 above)
Comment (otaviobp) [reply src/curl_async.c]: In reevaluate_number_of_parallel_downloads I save the last_retry, so we won't decrement the max_xfer in all calls. Only when the first download is retried by last_retry+1 times.

As we remove and add files to the failed list while we are trying to download, there will be files in the failed list in different retry numbers. Setting a last_retry variable was the only way I could think of on how to avoid the problem you commented.

File: src/curl.c [hunk 11]
```diff
@@ -340,6 +340,102 @@ CURLcode swupd_download_file_complete(CURLcode curl_ret, struct curl_file *file)
 	return curl_ret;
 }
 
+// err is only needed because retry code is spread all over swupd. Remove this error code return when
```
[the remark this answers is not in the document]
Comment (otaviobp) [reply src/curl.c]: good. I'll add that

File: src/curl_async.c (hunk 10 above)
Comment (castulo) [reply src/curl_async.c]: so what is your opinion on this @otaviobp ?
