### PR TITLE
Fix a bug in bundle-add --time

### LINKED ISSUE #675: bundle-add -t shows incorrect times
There are a couple of problems with the _-t_ option of bundle-add. 

The first problem is that it is now duplicating data. Before it used to print something like this:

```
Downloading packs...
	...100%
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.

Raw elapsed time stats:
      0.12 ms: Add bundles and recurse
      0.41 ms: Consolidate files from bundles
      0.08 ms: Download packs
      0.03 ms: Download missing files
      7.41 ms: Installing bundle(s) files onto filesystem

CPU process time stats:
      0.12 ms: Add bundles and recurse
      0.40 ms: Consolidate files from bundles
      0.08 ms: Download packs
      0.03 ms: Download missing files
      0.44 ms: Installing bundle(s) files onto filesystem
Successfully installed 1 bundle

Raw elapsed time stats:
      0.00 ms: Prepend bundles to list
    102.30 ms: Install bundles

CPU process time stats:
      0.00 ms: Prepend bundles to list
      1.36 ms: Install bundles
```

So even though it used to print _Raw elapsed time stats_ and _CPU process time stats_ twice, it was showing different data each time.

Now, it prints something like this:
```
Downloading packs...
	...100%
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.

Raw elapsed time stats:
    384.30 ms: Total execution time
      0.00 ms: Prepend bundles to list
      0.66 ms: Install bundles
      0.13 ms: Add bundles and recurse
      0.40 ms: Consolidate files from bundles
      0.08 ms: Download packs
      0.04 ms: Download missing files
     11.67 ms: Installing bundle(s) files onto filesystem
    117.31 ms: Run Scripts

CPU process time stats:
      6.12 ms: Total execution time
      0.00 ms: Prepend bundles to list
      0.66 ms: Install bundles
      0.13 ms: Add bundles and recurse
      0.40 ms: Consolidate files from bundles
      0.08 ms: Download packs
      0.04 ms: Download missing files
      0.40 ms: Installing bundle(s) files onto filesystem
      0.54 ms: Run Scripts
Successfully installed 1 bundle

Raw elapsed time stats:
    384.30 ms: Total execution time
      0.00 ms: Prepend bundles to list
      0.66 ms: Install bundles
      0.13 ms: Add bundles and recurse
      0.40 ms: Consolidate files from bundles
      0.08 ms: Download packs
      0.04 ms: Download missing files
     11.67 ms: Installing bundle(s) files onto filesystem
    117.31 ms: Run Scripts

CPU process time stats:
      6.12 ms: Total execution time
      0.00 ms: Prepend bundles to list
      0.66 ms: Install bundles
      0.13 ms: Add bundles and recurse
      0.40 ms: Consolidate files from bundles
      0.08 ms: Download packs
      0.04 ms: Download missing files
      0.40 ms: Installing bundle(s) files onto filesystem
      0.54 ms: Run Scripts
```

So it is basically the same data twice.

The second problem is that before _**Install bundles**_ would show the time for the whole installation process, since it included all the other sub tasks like: Add bundles and recurse, Consolidate files from bundles, Download packs, Download missing files, Installing bundle(s) files onto filesystem. Now the value shown in _Install bundles_ makes no sense since it is even smaller than one of its subtasks _Installing bundle(s) files onto filesystem_.

### PR DESCRIPTION
**Pull request by castulo**
This PR fixes a bug in bundle-add --time that was causing the command to show wrong values (and duplicated)

Closes #675

### CODE REVIEW

**Comment by castulo** [comment]
I didn't added a test for this code since @reaganlo already submitted a PR #641 for this, he will have to update the test with this output once merged.

File: src/bundle.c [hunk 1]
```diff
@@ -743,7 +743,7 @@ static int install_bundles(struct list *bundles, struct list **subs, struct mani
 	struct manifest *full_mom = NULL;
 
 	/* step 1: check bundle args are valid if so populate subs struct */
-	timelist_timer_start(global_times, "Add bundles and recurse");
+	timelist_timer_start(global_times, "    |-- Add bundles and recurse");
```
[the remark this answers is not in the document]
Comment (castulo) [reply src/bundle.c]: well I thought about that, but it seemed like a lot of unnecessary work (and complexity) for something that could be very easily done manually.

File: src/bundle.c [hunk 2]
```diff
@@ -838,7 +838,6 @@ static int install_bundles(struct list *bundles, struct list **subs, struct mani
 
 	mom->files = files_from_bundles(mom->submanifests);
 	mom->files = consolidate_files(mom->files);
-	timelist_timer_stop(global_times);
```
Comment (otaviobp) [inline src/bundle.c]: I'm reviewing this again and I don't understand why did you remove that stop. In that section we are counting how long does it take to download missing files and we are end on downloading after this step.

File: src/bundle.c [hunk 3]
```diff
@@ -975,7 +974,6 @@ static int install_bundles(struct list *bundles, struct list **subs, struct mani
 	timelist_timer_stop(global_times);
 
 	ret = 0;
-	timelist_print_stats(global_times);
```
Comment (otaviobp) [inline src/bundle.c]: this line needs to be removed. it's nice

File: src/bundle.c (hunk 2 above)
Comment (castulo) [reply src/bundle.c]: I had added comments on what timeliest_timer_stop was closing each timeliest_timer_start on my other commit that made it easier to see it. But that was in the commit I had for prettifying the output as tree, so I removed that. I will re-add those comments so we can more easily identify those changes.

Comment (castulo) [reply src/bundle.c]: so one of the timelist_timer_stop was extra in this section of the code, either the one at line 837 or the one at line 841. Maybe I should have removed the one at 837 instead of the one at 841 so it includes the file consolidation. @otaviobp should I move the timelist_timer_stop to line 841 instead?
