### PR TITLE
Checking mirror status only if it is set

### LINKED ISSUE #922: swupd update does not get content from the desired mirror
**Describe the bug**
swupd update does not get content from the desired mirror but from the default mirror with timeout. 

swupd info
Installed version: 28910
Version URL:       http://10.xxx.xx.xx/pub/mirrors/clearlinux/update
Content URL:       http://10.xxx.xx.xx/pub/mirrors/clearlinux/update

root@clr-node ~ # swupd update
Update started.
Error: Curl - Communicating with server timed out - 'https://cdn.download.clearlinux.org/update//version/format27/latest'
Waiting 10 seconds before retrying the download
Retry #1 downloading from https://cdn.download.clearlinux.org/update//version/format27/latest

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28910
 - Platform: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz

### PR DESCRIPTION
**Pull request by castulo**
When doing an update, we check to see if a mirror is stale, this only
needs to be done if there is a mirror set.

This commit checks to see if a mirror is set and only then it checks to
see if it is stale. This gives us the advantage of adding more detailed
messages when checking for the mirror status without polluting the output
with those extra messages when a mirror is not set.

Closes #922

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/mirror.c [hunk 1]
```diff
@@ -200,11 +200,34 @@ static enum swupd_code set_mirror_url(char *url)
...
 }
 
+static bool mirror_is_set(void)
+{
+	bool mirror_set;
+	char *version_path;
+	char *content_path;
+
+	version_path = mk_full_filename(path_prefix, MIRROR_VERSION_URL_PATH);
+	content_path = mk_full_filename(path_prefix, MIRROR_CONTENT_URL_PATH);
```
Comment (otaviobp) [inline src/mirror.c]: Content url isn't used by handle_mirror_if_stale, so it doesn't make sense to test mirror if version_path isn't set.

File: src/mirror.c [hunk 2]
```diff
@@ -221,10 +244,14 @@ void handle_mirror_if_stale(void)
 	 * will be used due to the diff being negative. */
 	int diff = central_version - mirror_version;
 	if (diff > MIRROR_STALE_UNSET || mirror_version == -1) {
```
Comment (otaviobp) [inline src/mirror.c]: error can be any number < 0 and not just -1

File: src/mirror.c [hunk 3]
```diff
@@ -221,10 +244,14 @@ void handle_mirror_if_stale(void)
 	 * will be used due to the diff being negative. */
 	int diff = central_version - mirror_version;
```
Comment (otaviobp) [inline src/mirror.c]: counting in this diff to decide if we get in or not is very fragile.
If we have errors on central_version and mirror_versions we're just getting into the if if mirror_version error is -1. But in this case I don't think it makes sense to unset the mirror, because we can have a connection problems.

So if the central_version is negative we should just ignore.
If the mirror_version has error or it's outdated and central_version works, we should unset the mirror.

File: src/mirror.c (hunk 1 above)
Comment (castulo) [reply src/mirror.c]: `handle_mirror_if_stale` only uses the version_url to see if the mirror is stale, but when a mirror is set, both version_url and content_url are set, so to actually claim that a valid mirror is set both of them would need to be set, wouldn't them? That is why I included both in the `mirror_is_set` function. Do you really think I should get rid of the content_url check in this function?

File: src/mirror.c (hunk 3 above)
Comment (castulo) [reply src/mirror.c]: ok I'll refactor that

Comment (castulo) [reply src/mirror.c]: done

**Comment by castulo** [comment]
Hey @otaviobp I think I addressed all your concerns with this update in the PR

File: src/curl.c [hunk 4]
```diff
@@ -150,6 +151,16 @@ static int check_connection(const char *test_capath)
 
 	switch (curl_ret) {
 	case CURLE_OK:
+		if (curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &response) != CURLE_OK) {
+			return -1;
+		}
+		/* when using http an invalid url will still return CURL_OK, we can consider
+		 * responses < 400 valid responses since they mean the request was received
+		 * and understood */
+		if (response >= 400) {
```
Comment (otaviobp) [inline src/curl.c]: We don't require that the server responds for requests to / so we can have a 404 here and it's fine.
This function is only checking if the server is up and if we can communicate with the server using ssl (in the case of https).
If it responds anything we're good to go. So don't worry about errors here.

File: src/curl.c [hunk 5]
```diff
@@ -173,7 +184,7 @@ static int check_connection(const char *test_capath)
 	}
 }
 
-int swupd_curl_init(void)
+int swupd_curl_init(char *url)
```
Comment (otaviobp) [inline src/curl.c]: ++ for that.

File: src/curl.c [hunk 6]
```diff
@@ -123,13 +123,14 @@ static CURLcode swupd_curl_set_timeouts(CURL *curl)
 	return curl_ret;
 }
 
-static int check_connection(const char *test_capath)
+static int check_connection(const char *test_capath, char *url)
 {
 	CURLcode curl_ret;
 	long response = 0;
+	char *connection_url = url ? url : version_url;
```
Comment (otaviobp) [inline src/curl.c]: It's a good idea to try to remove dependencies from swupd.h in this file. So take the version_url out. We can always use url. If url == NULL returns an error.

File: src/helpers.c [hunk 7]
```diff
@@ -579,7 +612,44 @@ enum swupd_code swupd_init(enum swupd_init_config config)
 	}
 
 	if ((config & SWUPD_NO_NETWORK) == 0) {
-		if (swupd_curl_init() != 0) {
+
+		bool curl_init = true;
+
+		/* try to init curl with whatever server is set up */
+		if (swupd_curl_init(NULL) != 0) {
```
Comment (otaviobp) [inline src/helpers.c]: use version_url here.

File: src/helpers.c [hunk 8]
```diff
@@ -579,7 +612,44 @@ enum swupd_code swupd_init(enum swupd_init_config config)
...
+			/* the server is not responding */
+			if (mirror_is_set()) {
+				/* the server is a mirror, check to see if the upstream server is working */
+				swupd_curl_deinit();
```
Comment (otaviobp) [inline src/helpers.c]: if curl_init fails it shouldn't be in a state where it's inited. this is a bug in curl_init. we need to run denit in culr_init if there's any errors.

File: src/helpers.c [hunk 9]
```diff
@@ -579,7 +612,44 @@ enum swupd_code swupd_init(enum swupd_init_config config)
...
+					curl_init = false;
+					free_string(&upstream_version_url);
+				}
+			} else {
+				/* the upstream server is not responding and there is no mirror */
+				curl_init = false;
+			}
+		}
+
+		if (!curl_init) {
```
Comment (otaviobp) [inline src/helpers.c]: this can move inside the if above because curl_init is never set to false outside of that if

File: src/helpers.c [hunk 10]
```diff
@@ -579,7 +612,44 @@ enum swupd_code swupd_init(enum swupd_init_config config)
...
+		if (swupd_curl_init(NULL) != 0) {
+			/* the server is not responding */
+			if (mirror_is_set()) {
+				/* the server is a mirror, check to see if the upstream server is working */
+				swupd_curl_deinit();
+				char *upstream_version_url = NULL;
+				get_upstream_version_url(&upstream_version_url);
+				if (upstream_version_url && swupd_curl_init(upstream_version_url) == 0) {
+					/* the upstream server is up, unset the mirror */
+					warn("The mirror '%s' is not responding\n", version_url);
```
Comment (otaviobp) [inline src/helpers.c]: If the mirror is offline we should hard fail, so we don't need to unset_mirror_url() here.
If the mirror is online, but outdated (or errors on downloading last version) we should unset the mirror and continue

File: src/curl.c (hunk 6 above)
Comment (castulo) [reply src/curl.c]: good idea

File: src/curl.c (hunk 4 above)
Comment (castulo) [reply src/curl.c]: good point. as long as we received a response we are good to go 👌

Comment (castulo) [reply src/curl.c]: ooh no, wait, I remember now why I added this....
If you add a fake http mirror, lets say "http://fakemirror.org/update", during check_connection it is going to respond with curl_ret = CURLE_OK, and response 404. But the server doesn't even exist, so that is why I think we need to check for valid responses.

Comment (castulo) [reply src/curl.c]: turns out that the proxy I'm connected to is the one responding instead of "http://fakemirror.org/update", this would be solved if using https, so we can basically ignore this at this point and allow it to continue, the command will fail further down the line anyway

Comment (castulo) [reply src/curl.c]: I'll remove that response check

File: src/helpers.c (hunk 7 above)
Comment (castulo) [reply src/helpers.c]: done

File: src/helpers.c (hunk 10 above)
Comment (castulo) [reply src/helpers.c]: true, I'll fix that

File: src/helpers.c (hunk 8 above)
Comment (castulo) [reply src/helpers.c]: I'll change that

File: src/helpers.c (hunk 10 above)
Comment (castulo) [reply src/helpers.c]: That is exactly how it was before... 😖 I guess there was a confusion somewhere

**Comment by castulo** [comment]
@otaviobp ok, I made some changes, I think it now works as expected

File: src/swupd.h [hunk 11]
```diff
@@ -388,6 +389,9 @@ extern void verify_set_picky_tree(char *picky_tree);
 /* repair.c */
 extern regex_t *compile_whitelist(const char *whitelist_pattern);
 
+/* mirror.c */
+extern bool mirror_is_set(void);
```
Comment (otaviobp) [inline src/swupd.h]: mirror_is_set() can now be a static method.

File: src/mirror.c [hunk 12]
```diff
@@ -206,46 +213,85 @@ static enum swupd_code set_mirror_url(char *url)
...
+
 	fullpath = mk_full_filename(path_prefix, DEFAULT_VERSION_URL_PATH);
 	int ret = get_value_from_path(&ret_str, fullpath, true);
 	if (ret != 0 || ret_str == NULL) {
 		/* no versionurl file here, might not exist under --path argument */
 		goto out;
 	}
+
+	/* before trying to get the latest version let's make sure the central version is up */
+	if (!content_url_is_local && !check_connection(NULL, ret_str)) {
```
Comment (otaviobp) [inline src/mirror.c]: check_connection returns an error int so the correct is
check_connection() != 0.

File: src/swupd.h (hunk 11 above)
Comment (castulo) [reply src/swupd.h]: true

File: src/mirror.c (hunk 12 above)
Comment (castulo) [reply src/mirror.c]: done

**Comment by castulo** [comment]
@otaviobp I addressed your comments in the last update
