### PR TITLE
Bug fix: os-install --bundles with os-core fails

### LINKED ISSUE #1369: swupd os-install: Error: Missing --bundle argument
Our container builds have:

```
RUN mkdir /install_root \
    && swupd os-install \
    ${CLEAR_LINUX_VERSION} \
    --path /install_root \
    --statedir /swupd-state \
    --bundles=os-core \
    --no-boot-update \
    && rm -rf /install_root/var/lib/swupd/*
```

but is has started failing with an error: `Error: Missing --bundle argument`

There's no documentation about `--bundle`. 

However, if I change  to `--bundles=os-core,vi` (as shown by the help text), this starts working*. It looks `os-core` is somehow ignored/skipped and if the list becomes empty the error is given.

(* However, `vi` gives `Warning: Bundle "vi" is invalid or no longer available`)

### PR DESCRIPTION
**Pull request by castulo**
When doing a system install with "os-install --bundles" if the list of
bundles to install includes only "os-core" the install fails.

This commit fixes the issue.

Closes #1369 

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/os_install.c [hunk 1]
```diff
@@ -87,15 +87,18 @@ static bool parse_opt(int opt, char *optarg)
 	case 'B': {
 		char *arg_copy = strdup_or_die(optarg);
 		char *token = strtok(arg_copy, ",");
+		bool oscore_requested = false;
 		while (token) {
-			if (strcmp(token, "os-core") != 0) {
+			if (strcmp(token, "os-core") == 0) {
```
Comment (otaviobp) [inline src/os_install.c]: Why we just don't add os-core to the list?

Comment (castulo) [reply src/os_install.c]: To be honest, IDK 🤣 , I assumed we had a reason no to, so I kept the same code logic. But now that I'm looking at the code I cannot find a reason why not to. I'll take a closer look and will run a few tests, if everything looks good I'll just add it as you mentioned.

**Comment by castulo** [comment]
V2: I just tested the fix as @otaviobp suggested just by allowing os-core to be added to the bundles list when requested, and it works fine. So this update includes that change.
