### PR TITLE
Continue with update when a bundle was removed upstream

### LINKED ISSUE #624: Error updating if bundles went missing from mix.
Scenario:
- mix with bundle X
- remove X from mix
- swupd on client with bundle X installed
- swupd fails to update

```
# swupd update
Update started.
Preparing to update from 140 to 150
Warning: Bundle "xemacs" is invalid, skipping it...
Warning: Bundle "openssl" is invalid, skipping it...
Update took 0.2 seconds
# echo $?
14
```

This should probably continue, or print a really serious error message. Especially auto-updates should succeed at any cost...

### PR DESCRIPTION
**Pull request by castulo**
If a bundle happens to be removed from the content server (or mix) it
means the bundle won't be in the MoM anymore, so the bundle in the
system will look like an invalid bundle. When this happens the update
is currently stopping.

This PR fixes this so If this happens, the user is informed, and
the update continues.

Closes #624

Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>

### CODE REVIEW

File: src/update.c [hunk 1]
```diff
@@ -395,8 +395,14 @@ static int main_update()
 	ret = add_included_manifests(server_manifest, &latest_subs);
 	timelist_timer_stop(global_times);
 	if (ret) {
-		ret = EMANIFEST_LOAD;
-		goto clean_exit;
+		if (ret == -add_sub_BADNAME) {
```
Comment (evil-brain) [inline src/update.c]: I know these definitions are already merged, but it feels odd to have constant names mix case.

File: src/update.c [hunk 2]
```diff
@@ -395,8 +395,14 @@ static int main_update()
...
+			/* this means a bundle(s) was removed in a future version */
+			printf("WARNING: One or more installed bundles are no longer available at version %d.\n",
```
Comment (evil-brain) [inline src/update.c]: Seems swupd prints most warnings to stderr. Not asking to change this in this commit, because there are other examples in the code where warnings are printed to stdout.

File: src/update.c (hunk 1 above)
Comment (castulo) [reply src/update.c]: true

File: src/update.c (hunk 2 above)
Comment (castulo) [reply src/update.c]: yes, there is an open issue that talks about that #294
