### PR TITLE
delta: Improve message on delta errors

### LINKED ISSUE #1425: Improve messaging on swupd update when delta file fails
When `swupd update` is run and there are delta files that can't apply, we print a warning error that is more focused on debugging the issue than explaining the problem to the user. Current message is
```
Warning: Couldn't use delta file /var/lib/swupd/delta/32750-32760-a30e825b9ac1ac220453ba191442d25e16687aee450476409cb4c304d094a803-a30e825b9ac1ac220453ba191442d
25e16687aee450476409cb4c304d094a803: 'from' file corrupted on system, consider running 'swupd verify --fix'
```

We could print something like:
```
Warning: /usr/lib/foo/bar was changed from the installed version. Replacing.
Consider running 'swupd repair' to restore any other files that were modified.
```

### PR DESCRIPTION
**Pull request by otaviobp**
Print a more useful error when we fail to locate a file to apply a
delta. Add a suggestion for the user to run `swupd repair` and make
it clear that the problem is in their system and not in the update
content.

Fixes #1425

Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>

### CODE REVIEW

File: src/swupd_lib/delta.c [hunk 1]
```diff
@@ -168,20 +167,15 @@ void apply_deltas(struct manifest *current_manifest)
 
 			if (!compute_hash_from_file(filename, hash) || !hash_equal(file->hash, hash)) {
 				FREE(filename);
-				bad_on_sys = true;
+				warn("File '%s' is missing or corrupted - consider running 'swupd repair'\n", file->filename);
```
Comment (castulo) [inline src/swupd_lib/delta.c:170]: In other parts of the code when we show this type of warning we do it in two steps:
```
warn("My warning\n");
info("My suggestion\n");
```
You can see an example of this here: https://github.com/clearlinux/swupd-client/blob/master/src/cmds/verify.c#L673
Also I would use "command" instead of 'command' as in the example above to keep it consistent.

Comment (otaviobp) [reply src/swupd_lib/delta.c]: cool, I followed your suggestion. Can you take another look

Comment (castulo) [reply src/swupd_lib/delta.c]: Looks good, the only thing you didn't do was using "" instead of `` like this:
`info("Consider running /"swupd repair/" to fix the issue\n");`

File: src/swupd_lib/delta.c [hunk 2]
```diff
@@ -168,20 +167,16 @@ void apply_deltas(struct manifest *current_manifest)
...
 		}
 
 		if (!found) {
-			warn("Couldn't use delta file %s\n", delta_file);
-			if (bad_on_sys) {
-				info("'from' file corrupted on system, consider running 'swupd verify --fix'\n");
-			} else {
-				info("no 'from' file to apply was found\n");
-			}
+			warn("Couldn't use delta file becase original file is corrupted or missing\n");
```
Comment (phmccarty) [inline src/swupd_lib/delta.c:178]:
```suggestion
			warn("Couldn't use delta file because original file is corrupted or missing\n");
```

File: test/functional/update/update-verify-fix-path-missing-dir.bats [hunk 3]
```diff
@@ -26,7 +26,9 @@ test_setup() {
 		Downloading packs for:
 		 - test-bundle
 		Finishing packs extraction...
-		Warning: Couldn.t use delta file .*
+		Warning: File '/foo/bar/baz/test-file' is missing or corrupted
+		Warning: Couldn't use delta file becase original file is corrupted or missing
```
Comment (phmccarty) [inline test/functional/update/update-verify-fix-path-missing-dir.bats:30]:
```suggestion
		Warning: Couldn't use delta file because original file is corrupted or missing
```

**Comment by otaviobp** [comment]
V3: Fixing typo and replacing ' by "
